creation_rules:
  # Encrypt all secrets in k8s/clusters/*/secrets/ directories
  - path_regex: k8s/clusters/.*/secrets/.*\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0

  # Encrypt any file with .sops.yaml or .secret.yaml suffix
  - path_regex: .*\.sops\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0

  - path_regex: .*\.secret\.ya?ml$
    encrypted_regex: ^(data|stringData)$
    age: age1hhwgd0zzsuqrg7gad42kh547lkgfeqsu03uql375uzslz0vqc37sknuux0
