apiVersion: v1
kind: Secret
metadata:
    name: worker-ssh-key
    namespace: k0smotron
type: Opaque
data:
    #ENC[AES256_GCM,data:T/csqCMIXvxUIL4P/Pwhd4zrsUpOKqQeLCYaR0Ye5iup03rthMecIw==,iv:qica0e2HIUSNLJsLXmpQeBBPkVOzpa9D3EamSQpTTNw=,tag:x+UBRsbext1hF8iinrBMSw==,type:comment]
    id_ed25519: ENC[AES256_GCM,data:2hbTyc7Hd7oKAjNvbmLsibBPouAJtMP9zwK06wvv0//XPKI4MlisMdP1D8YIpnKnqKfNDzBKfQjoeDIhsUknPBaXvva0S93fMPAyd12PaNoIkhIV8L8ijRZs27eqa9H9rdpPnyBGs2yXa4xdix/HHWUI3RD0H9MhJU4cvYWnAha6Ln4Ws12ZsBgoKBq6N7QgLuEoLEra+tXs/NTE3GzrXw3ISxngFJtIk7+pkhl5vN7eyvn14a47N9eodTvOz0osbCUQ+SiLulCg58h73dMZeFEay7xoqjnJSErEyGZZNjzAGl89X06Ki7H5UQnTf4fE/KmGGA5ozkksjYZYR8OrQlcGkpSftRwXZ9/Pzd3kqT5XXYNB6sKK2ZOghCLz1oAEiGDxs02BIi4laVUsrCPYepHSnTzzGtCMjiYBbOkoS783mNQeOsccBzp49AV9PYtIinnfWYiGIPUYQ/BKron+kqo79z06JyIApVMTY0G3QOSrwNm0+wg/FCuFkGDl/Fjx21mh54G4UtyFMjAe55pVyk8YQXPvyENFJK0P7qGGV21wk1+rf47L0HfmCzrOkqHuai/n/j2LtcuL2Ga8pJOxL38EAVADwTCS9oZM+tlt/pZ0nM1t6Zx852UfFYGeQK+nZpxzGPN6s3WAl0dfo0HqkuB3bHeD+wXeuIIT0B8vbqNYF3a0,iv:A9X7FvIsq8mP39O7woEiETzFpVBF+YBessK8cyVDLhQ=,tag:aGQ7TcHn5LJncN9ocyHRUQ==,type:str]
sops:
    age:
        - recipient: ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIMMWCN1efjHi2e7k13kCFPo4wKyH8zxPFL06CAKpSaNU
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IHNzaC1lZDI1NTE5IDNmN2h6QSAwdjJI
            dnJUYUVuV1AwcTRKYjVpYm9DdTNKTzhUOFVOUUhuUEpqZEJMdUY4CklqeGFzUlBJ
            amxCdXR0Y2ZLZVhXdTFnNHliYVIzL2hoRzNlYUwxUXNlNzQKLS0tIGZxdlJMSThJ
            TFBuWUNkbzVQV1lLN0k0MVFJa2dwSjVkcUJTeFRXQzB3UmMKq7EPO24QO3F3ULAZ
            EurjNbIh4a+FzumuNYtRnJltz6AZqsigm0olCCtg9s6uB19lTG7YaWnUCrIJGNx5
            PIB6fQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-10-29T20:44:47Z"
    mac: ENC[AES256_GCM,data:sE61Uv13ouoGqjagW/f6RYhktT8cOuVcrKdX2YC8CxL3UBY340JBixT1JC36p+4vcuHZEj6RCu3PXjSSf7HjUbPdXPyMdcWwqHd9lPc7PL+HrQ+rbmAKrAKijNv9vMXAbpdJ8S7N6zp26b3umsZQpdU5ReZbNkZei8vLf33WYEw=,iv:yiu28nKYRUQ76WX7JDgF4HbYKWwcUc5ESolSWscEhyI=,tag:9kTr2q5u7gpqXpq3Niub6w==,type:str]
    encrypted_regex: ^(data|stringData)$
    version: 3.10.2
