apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 1m
  ref:
    branch: main
  url: ssh://git@github.com/your-user/homelab
  ignore: |
    # Exclude non-k8s directories
    /terraform/
    /ansible/
    /docs/
    /scripts/
    /.github/
---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: flux-system
  namespace: flux-system
spec:
  interval: 10m
  path: ./k8s/clusters/management
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
