---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: pocket-id
  namespace: pocket-id
spec:
  interval: 30m
  chart:
    spec:
      chart: pocket-id
      version: "*"
      sourceRef:
        kind: HelmRepository
        name: pocket-id
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    image:
      repository: ghcr.io/pocket-id/pocket-id
      tag: v1
      pullPolicy: IfNotPresent

    # Application Configuration
    config:
      APP_URL: "https://auth.jax-lab.dev"
      TRUST_PROXY: "true"
      ENCRYPTION_KEY: "C0VMk+NxiHcc/CRvORp6zNfOW5L3NaUON/rremGhonA="

    # Service Configuration
    service:
      type: ClusterIP
      port: 80

    # Persistence
    persistence:
      enabled: true
      size: 2Gi
      accessMode: ReadWriteOnce
      storageClass: openebs-zfs-homelab
      existingClaim: pocket-id-data

    # Health Checks
    livenessProbe:
      enabled: true
      initialDelaySeconds: 30
      periodSeconds: 30
      timeoutSeconds: 5
      failureThreshold: 3

    readinessProbe:
      enabled: true
      initialDelaySeconds: 5
      periodSeconds: 10
      timeoutSeconds: 5
      failureThreshold: 3

    # Pod Configuration
    podSecurityContext:
      fsGroup: 1000
      runAsNonRoot: true
      runAsUser: 1000

    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        drop:
          - ALL
      readOnlyRootFilesystem: false

    # Resources
    resources:
      requests:
        cpu: 100m
        memory: 128Mi
      limits:
        cpu: 500m
        memory: 512Mi

    # ServiceAccount
    serviceAccount:
      create: true
      automount: true
      name: pocket-id
