---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pocket-id-data
  namespace: pocket-id
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: openebs-zfs-homelab
  resources:
    requests:
      storage: 2Gi
