apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: cloud-cluster
  namespace: k0smotron
spec:
  replicas: 1
  version: v1.32.8
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    spec:
      extensions:
        helm:
          repositories:
          - name: traefik
            url: https://traefik.github.io/charts
          charts:
          - name: traefik
            chartname: traefik/traefik
            version: "37.2.0"
            namespace: traefik
            values: |
              service:
                type: NodePort
