apiVersion: k0smotron.io/v1beta1
kind: Cluster
metadata:
  name: sandbox-cluster
  namespace: k0smotron
spec:
  replicas: 1
  version: v1.32.8
  k0sConfig:
    apiVersion: k0s.k0sproject.io/v1beta1
    kind: ClusterConfig
    spec:
      extensions:
        helm:
          repositories:
          - name: traefik
            url: https://traefik.github.io/charts
          - name: bitnami
            url: https://charts.bitnami.com/bitnami
          charts:
          - name: metallb
            chartname: bitnami/metallb
            version: "6.4.22"
            namespace: metallb-system
            values: |
              configInline:
                address-pools:
                - name: sandbox-pool
                  protocol: layer2
                  addresses:
                  - 192.168.8.50-192.168.8.79
          - name: traefik
            chartname: traefik/traefik
            version: "37.2.0"
            namespace: traefik
