---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 24h
  url: https://metallb.github.io/metallb
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metallb
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: metallb
      version: 0.14.x
      sourceRef:
        kind: HelmRepository
        name: metallb
        namespace: flux-system
  targetNamespace: metallb-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    # MetalLB values - resources created post-install via postRenderers not supported
    # Will create IPAddressPool separately after chart installs
