---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 37.2.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  targetNamespace: traefik
  install:
    createNamespace: true
    remediation:
      retries: 3
  values:
    # Service configuration
    service:
      type: LoadBalancer
      annotations:
        metallb.universe.tf/loadBalancerIPs: 192.168.8.50

    # Persistent storage for Let's Encrypt certificates
    persistence:
      enabled: true
      storageClass: openebs-zfs-homelab
      size: 1Gi
      path: /data

    # Security context to allow writing to persistent volume
    # fsGroupChangePolicy prevents Kubernetes from recursively chmod'ing files to 660
    # This allows Traefik to create acme.json with correct 600 permissions
    podSecurityContext:
      fsGroup: 65532
      fsGroupChangePolicy: "OnRootMismatch"

    # Let's Encrypt configuration with DNS-01 challenge
    additionalArguments:
      - "--certificatesresolvers.letsencrypt.acme.email=admin@jax-lab.dev"
      - "--certificatesresolvers.letsencrypt.acme.storage=/data/acme.json"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge=true"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.provider=cloudflare"
      - "--certificatesresolvers.letsencrypt.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"

    # Environment variables for Cloudflare API token
    env:
      - name: CF_DNS_API_TOKEN
        valueFrom:
          secretKeyRef:
            name: cloudflare-api-token
            key: CF_DNS_API_TOKEN

    # Enable IngressRoute CRD
    ingressRoute:
      dashboard:
        enabled: false

    # Allow ExternalName services for Home Assistant
    providers:
      kubernetesCRD:
        allowExternalNameServices: true
