---
apiVersion: source.toolkit.fluxcd.io/v1
kind: HelmRepository
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 24h
  url: https://traefik.github.io/charts
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: traefik
  namespace: flux-system
spec:
  interval: 30m
  chart:
    spec:
      chart: traefik
      version: 37.2.x
      sourceRef:
        kind: HelmRepository
        name: traefik
        namespace: flux-system
  targetNamespace: traefik
  install:
    createNamespaces: true
    remediation:
      retries: 3
  values:
    service:
      type: LoadBalancer
